chdir: /var/apps/mattchandlersaid/mattchandlersaid/
pid: tmp/pids/thin.pid
log: log/thin.log
timeout: 30
max_conns: 1024
port: 4100
max_persistent_conns: 512
chdir: /var/apps/mattchandlersaid/ 
environment: production 
servers: 5
daemonize: true
